Repository nclskfm/dhbw-studienarbeit-muehle, pull requests merged in 2021-06, with the labels that each got.

#184 #185 Optimized Cache by normalization
  jupyter/nmm-cache.ipynb
Labels: rote

#190 Fix: Changed the is operator on a string literal to ==
  jupyter/nmm-cache.ipynb
Labels: bug, rote

#192 #186 Implement Rote Training
  README-hausarbeit-rote-learning.md
  jupyter/nmm-cache.ipynb
  jupyter/nmm-rote-training.ipynb
  jupyter/nmm-tournament.ipynb
Labels: IMPORTANT, rote

#193 Fix: Cache.clean() start min_limit always as 0
  jupyter/nmm-alpha-beta-pruning.ipynb
  jupyter/nmm-cache.ipynb
Labels: bug, rote

#195 Added Section about Rote-Learning Training
  Dockerfile
  jupyter/nmm-rote-learning.ipynb
  jupyter/nmm-rote-training.ipynb
Labels: rote

#196 Fixed not saving at the end of rote training
  jupyter/nmm-rote-training.ipynb
Labels: bug, rote

#197 Fixed wrong tqdm usage in tournament
  jupyter/nmm-tournament.ipynb
Labels: bug

#198 Added more Text and Cell for evaluation
  Dockerfile
  README-hausarbeit-rote-learning.md
  docker-compose.yaml
  jupyter/nmm-alpha-beta-pruning.ipynb
  jupyter/nmm-cache.ipynb
  jupyter/nmm-rote-learning.ipynb
  jupyter/nmm-rote-performance-testing.ipynb
  jupyter/nmm-rote-training.ipynb
  jupyter/rounds-rote-learning/round-small-full-0-seed-1.txt
  jupyter/rounds-rote-learning/round-small-full-0-seed-2.txt
  jupyter/rounds-rote-learning/round-small-full-1-seed-1.txt
  jupyter/rounds-rote-learning/round-small-full-1-seed-2.txt
  jupyter/rounds-rote-learning/round-small-full-10-seed-1.txt
  jupyter/rounds-rote-learning/round-small-full-2-seed-1.txt
  jupyter/rounds-rote-learning/round-small-full-2-seed-2.txt
  jupyter/rounds-rote-learning/round-small-full-3-seed-1.txt
  jupyter/rounds-rote-learning/round-small-full-3-seed-2.txt
  jupyter/rounds-rote-learning/round-small-full-4-seed-1.txt
  jupyter/rounds-rote-learning/round-small-full-4-seed-2.txt
  jupyter/rounds-rote-learning/round-small-full-5-seed-1.txt
  jupyter/rounds-rote-learning/round-small-full-5-seed-2.txt
  jupyter/rounds-rote-learning/round-small-full-6-seed-1.txt
  jupyter/rounds-rote-learning/round-small-full-6-seed-2.txt
  jupyter/rounds-rote-learning/round-small-full-7-seed-1.txt
  jupyter/rounds-rote-learning/round-small-full-7-seed-2.txt
  jupyter/rounds-rote-learning/round-small-full-8-seed-1.txt
  jupyter/rounds-rote-learning/round-small-full-8-seed-2.txt
  jupyter/rounds-rote-learning/round-small-full-9-seed-1.txt
  jupyter/rounds-rote-learning/round-small-full-9-seed-2.txt
Labels: rote

#203 #201 rote learning export
  Hausarbeit-Rote-Learning.pdf
  README.md
  tex/rote/rote-combined.tex
Labels: IMPORTANT, docs, rote

#225 #219 Deleted nmm-cache as it is unused in the branch
  jupyter/nmm-cache.ipynb
Labels: bug, meta

#229 #209 Fixed style.html Header
  jupyter/nmm-alpha-beta-pruning.ipynb
  jupyter/nmm-artificial-intelligence.ipynb
  jupyter/nmm-conclusion.ipynb
  jupyter/nmm-game-utils.ipynb
  jupyter/nmm-game.ipynb
  jupyter/nmm-gui-utils.ipynb
  jupyter/nmm-gui.ipynb
  jupyter/nmm-heuristic.ipynb
  jupyter/nmm-minimax.ipynb
  jupyter/nmm-symmetry.ipynb
  jupyter/nmm-tournament.ipynb
Labels: bug, docs, meta

#231 #215 Fixed typo in symmetryDiagonal
  jupyter/nmm-symmetry.ipynb
Labels: bug, docs

#232 #213 Added helper function for pounding mills and stones
  jupyter/nmm-game-utils.ipynb
  jupyter/nmm-game.ipynb
Labels: game, meta

#237 #217 Fixed strange comments in AlphaBeta and Minimax
  jupyter/nmm-alpha-beta-pruning.ipynb
  jupyter/nmm-minimax.ipynb
Labels: alphaBeta, bug, docs, minimax

#238 #236 Comment about Tournament on Windows
  jupyter/nmm-tournament.ipynb
Labels: bug, docs

#239 Fixed tex export bug for lists
  jupyter/nmm-alpha-beta-pruning.ipynb
  jupyter/nmm-game.ipynb
  jupyter/nmm-gui-utils.ipynb
  jupyter/nmm-gui.ipynb
  jupyter/nmm-heuristic.ipynb
  jupyter/nmm-minimax.ipynb
  jupyter/nmm-symmetry.ipynb
  jupyter/nmm-tournament.ipynb
Labels: bug, meta

#241 Master aktualisierung auf die neueste Version der Studienarbeit
  Studienarbeit.pdf
  jupyter/nmm-alpha-beta-pruning.ipynb
  jupyter/nmm-artificial-intelligence.ipynb
  jupyter/nmm-conclusion.ipynb
  jupyter/nmm-game-utils.ipynb
  jupyter/nmm-game.ipynb
  jupyter/nmm-gui-utils.ipynb
  jupyter/nmm-gui.ipynb
  jupyter/nmm-heuristic.ipynb
  jupyter/nmm-minimax.ipynb
  jupyter/nmm-symmetry.ipynb
  jupyter/nmm-tournament.ipynb
  tex/studienarbeit.tex
Labels: meta
