Repository nclskfm/dhbw-studienarbeit-muehle, pull requests merged in 2021-04, with the labels that each got.

#139 #134 Simplified findMills function
  jupyter/nmm-game-utils.ipynb
Labels: game, meta

#141 #140 set environment PYTHONHASHSEED=0
  docker-compose.yaml
Labels: meta

#138 #113 Simplified move function
  jupyter/nmm-game-utils.ipynb
Labels: game, meta

#142 #123 Heuristic: possible mills and weights
  jupyter/nmm-game-utils.ipynb
  jupyter/nmm-heuristic.ipynb
Labels: alphaBeta, game, minimax

#150 #126: fix order of orderMove(s, p)
  jupyter/nmm-alpha-beta-pruning.ipynb
Labels: alphaBeta, bug

#149 #143 Implementierung der abstrakten Superklasse für KI
  jupyter/nmm-artificial-intelligence.ipynb
Labels: IMPORTANT, alphaBeta, minimax

#152 #144 Implemented AI super class for Minimax
  jupyter/nmm-minimax.ipynb
Labels: meta, minimax

#154 Moved bestMove() to BestMoves.choice()
  jupyter/nmm-artificial-intelligence.ipynb
Labels: bug

#153 #145 Implemented AI super class for AlphaBeta
  jupyter/nmm-alpha-beta-pruning.ipynb
  jupyter/nmm-minimax.ipynb
Labels: alphaBeta, meta

#156 #125: Add Limit to Cache
  jupyter/nmm-alpha-beta-pruning.ipynb
Labels: alphaBeta

#164 Added Cache Notebook
  jupyter/nmm-cache.ipynb
Labels: rote

#167 #148 Added README and reading order
  README.md
  images/player-vs-alphabetapruning.png
  jupyter/README-hausarbeit-retrograde-analysis.md
  jupyter/README-hausarbeit-rote-learning.md
  jupyter/README-studienarbeit.md
Labels: meta

#170 Removed unused tests
  jupyter/tests/nmm-test-example.ipynb
  jupyter/tests/nmm-test-utils.ipynb
  jupyter/tests/nmm-test.ipynb
Labels: meta, test

#168 #132 Reformatted long lines
  jupyter/nmm-alpha-beta-pruning.ipynb
  jupyter/nmm-game-utils.ipynb
  jupyter/nmm-gui-utils.ipynb
  jupyter/nmm-gui.ipynb
Labels: meta

#172 #130: better explanation of iterative deepening
  jupyter/nmm-alpha-beta-pruning.ipynb
Labels: alphaBeta, docs
